### ISSUE TITLE
Map System Overhaul

### ISSUE THREAD

**Issue by stewartmatheson** [stewartmatheson/projectx#26]
Currently our map data for a given house scene is represented by one single vector of tiles.

```c++
std::vector<Tile> tiles
```
While this keeps things simple such as reading and writing binary map files it does pose limitations. These limitations are

 * Each map can only ever have one single `struct` describing it's data
 * This map would have to use some union type which might make writing out binary map files harder to manage.

This limitation was reached when building the new `Entity` system. See README for details on how that system is intended to work. It's clear we have a need for a much more flexible data structure. This structure should allow for multiple tile layers for background map tiles as well as supporting different data structures in the future. This structure should provide all map data to any component that requires it including `HouseScene` and `TilePaletteView`.  See the following example for an idea of what the new struct will look like. 

```c++
struct TileLayer {
    int layer_index;
    std::vector<Tile> tiles; // Note this is the existing map tile type
}

struct Map {
    int version;
    std::vector<TileLayer> tile_layers;
    std::vector<FileEntity> entites;
    std::vector<FutureStruct> future_struct; // This does not exist however we a legacy map is loaded we can just init an empty list.
}

struct FileEntity {
    EntityType type
    int x;
    int y;
    int rotation;
}

// Creating the runtime entities via a factory pattern
Entity create_entity(FileEntity entity) {
    if (entity.type == EntityType.Player) {
       return create_player_entity(x, y, rotation);
    }
}

```
Having a single map struct will allow for multiple tile layers within a single map allowing these layers to be rendered in order using the layout index. This can be advantageous as it allows for smaller sprite sheets and more dynamic level designs.  The entity list will cover all the entities contained within the map. With this arrangement we will be able to add future structs to binary files without having to break backward compatibility. 

Given this a binary file could be layered out in the following way, pipes delimit the segments.

```
map_version | layer_count | tile_in_layer_count | layer_tiles... | tile_in_layer_count | layer_tiles... | entity_count | entites... | future_struct_count | future_struct...
```

**Comment by stewartmatheson** [comment]
Thoughts @msbit

**Comment by msbit** [comment]
That layout looks good to me.

> This can be advantageous as it allows for smaller sprite sheets and more dynamic level designs

So with what you have described there, does each `TileLayer` have a separate `SpriteSheet` that it will use for editting and rendering? If so, is it worth considering some reference in the saved file to the sprite sheet file, or it that unnecessary generalising at this stage? 

One other thing I would suggest, if you're looking at a change of the file format, is a header at the start, with (perhaps a magic string and) a version. This would allow doing something sensible in the case of a backward incompatible change.

**Comment by msbit** [comment]
Oh and one other thing that just occurred to me, will serialising the entities be simple (as in, fixed size for each) or do you see any kind of inheritance / additional fields that need to be stored for some of the types?

Either way, one thing to check would be that `EntityType` has the same underlying integers for each case (possibly something mandated by the spec) if `Entity` is going to be serialised as per the `Tile`s with a `reinterpret_cast`.

**Comment by stewartmatheson** [comment]
Hey @msbit  I don't think I will have a sprite sheet link in this first version. I'm happy to load all tiles from one sheet for now. It's a good point though however I would not be 100% clear on how we would reference different sheets. Naming convention? Perhaps we can just write them to binary as well. It looks like SFML makes it easy to read from different formats if we need to. https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Texture.php 

With the entity classes I would see a factory pattern driving their creation. We could have some other struct in the binary file, read that and then call the correct factory method. That way we would not have to put in things like animation frames in to the binary file which at this point I would feel is best kept in the code as I don't think there will be too many different entities. I'm trying to keep the game design small. I'll update the ticket.

**Comment by stewartmatheson** [comment]
merged in!!!

**Comment by msbit** [comment]
Nice one.

Definitely a better, more flexible structure for the data.
