### ISSUE TITLE
Automated formatting :)

### ISSUE THREAD

**Issue by msbit** [stewartmatheson/projectx#46]
Just wanted to raise the possibility of choosing an automated formatter for the project. If you wanted to look into it, I'm partial to [`clang-format`](https://clang.llvm.org/docs/ClangFormat.html) which I usually just run as-is (I actually don't know if it can be configured), but any tool you like the look of I'd be happy with.

**Comment by stewartmatheson** [comment]
Hey Tom,

Yeah I like these kind of tools. I'll have a look at getting it in to the project in some kind of automated way. That page you linked to has some notes about vim which is good. Another option is git commit hooks which are handy too.  I'm about to merge in the huge refactor. Let me know your thoughts. I'm happy I got there in the end. I'm going to be able to now focus on building in more features to the map editor now so we can hopefully get some game play working.

**Comment by msbit** [comment]
Sounds good.

I'm happy with any level of automation, really, even if it's just agreeing on  tool and running it now and then when we remember to do so :)

**Comment by stewartmatheson** [comment]
https://github.com/stewartmatheson/projectx/commit/583de5d59e97eeb2a1a0a232c1b6827aeadbe0ed

got a format file and I have setup formatting on on save. Feel free to change the format to anything your comfortable with.
